* bugfix

diff --git a/cocsign b/cocsign
--- a/cocsign
+++ b/cocsign
@@ -2,25 +2,28 @@
 # Made by Eduardo Echeverria, Hector Mantellini, Jesus Palencia
 # Licence: GPL-2
 LC_ALL=C
-
-if [[ "$EUID" = "0" ]]; then
-	echo -e "\e[00;31mERROR: NO DEBES SER ROOT\e[00m"
-	exit 1
-fi
-
 minombre="UbuntuCodeofConduct-2.0.txt"
+
 function pause() {
 	read -p "$*"
 }
 
 case "$1" in
 	instalar)
-		sudo echo -e "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse""\n""deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse""\n""deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" > /etc/apt/sources.list
-		sudo apt -q update && apt -qy install gnupg wget gedit xclip
+		if [[ "$EUID" != "0" ]]; then
+			echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+			exit 1
+		fi
+		echo -e "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse""\n""deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse""\n""deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" > /etc/apt/sources.list
+		apt -q update && apt -qy install gnupg wget gedit xclip
 		echo "Instalacion finalizada..."
 		;;
 
 	iniciar)
+		if [[ "$EUID" = "0" ]]; then
+			echo -e "\e[00;31mERROR: NO DEBES SER ROOT\e[00m"
+			exit 1
+		fi
 		rm -f /tmp/genkey
 		rm -f /tmp/listo
 		rm -f /tmp/descifrado
