se elimino CAT y se dejo solo xclip en captura de ssh

diff --git a/cocsign b/cocsign
--- a/cocsign
+++ b/cocsign
@@ -1,112 +1,137 @@
 #!/usr/bin/env bash
-# Made by Eduardo Echeverria, Hector Mantellini, Jesus Palencia
+# Made by Jesus Palencia, Hector Mantellini
 # Licence: GPL-2
-
-set -eu
 LC_ALL=C
+minombre="UbuntuCodeofConduct-2.0.txt"
 
 function pause() {
 	read -p "$*"
 }
 
+
+function check () {
+	clear
+	if [[ "$EUID" = "0" ]]; then
+		echo -e "\e[00;31mERROR: No debe ser root.\e[00m"
+		exit 1
+	fi
+	if ! [[ -f /usr/bin/xclip ]]; then
+		echo -e "\e[00;31mDebe ejecutar la instalacion antes de continuar.\e[00m"
+		exit 1
+	fi
+}
+
 case "$1" in
 	instalar)
-		sudo apt -q update
-		sudo apt -q install gnupg wget gedit xclip
-		echo "Finalizado..."
+		clear
+		if [[ "$EUID" != "0" ]]; then
+			echo -e "\e[00;31mERROR: Debe ser root.\e[00m"
+			exit 1
+		fi
+		cp /etc/apt/sources.list /etc/apt/sources.list.old
+		echo -e "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse""\n""deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse""\n""deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" > /etc/apt/sources.list
+		apt -q update
+		apt -qy install gnupg wget xclip beep
+		mv -f /etc/apt/sources.list.old /etc/apt/sources.list
+		echo -e "\e[00;1;92mInstalacion finalizada...\e[00m"
 		;;
 
-	iniciar)
-		echo -e "\e[00;31mScript para firmar el código de conducta de UBUNTU\e[00m"
-		if ! [[ -f "$HOME"/UbuntuCodeofConduct-2.0.txt ]]; then
-			echo "Descargando codigo de conducta 2.0"
-			wget -q -O "$HOME"/UbuntuCodeofConduct-2.0.txt - https://launchpad.net/codeofconduct/2.0/+download
+	gpg)
+		check
+		rm -f /tmp/genkey
+		rm -f /tmp/listo
+		rm -f /tmp/descifrado
+		rm -f "$HOME"/correo.gpg
+		if ! [[ -f "$HOME"/"$minombre" ]]; then
+			echo -e "\e[00;1;92mDescargando codigo de conducta.\e[00m"
+			wget -v -O "$HOME"/"$minombre" https://launchpad.net/codeofconduct/2.0/+download
+			echo ""
+			echo -e "\e[00;1;92mDescarga finalizada.\e[00m"
 		fi
-		echo "Generando llave"
-		
+		echo ""
+		echo -e "\e[00;1;92mGenerando llave GPG\e[00m"
 		echo 'Key-Type: 1' > /tmp/genkey
 		echo 'Key-Length: 2048' >> /tmp/genkey
 		echo 'Subkey-Type: 1' >> /tmp/genkey
 		echo 'Subkey-Length: 2048' >> /tmp/genkey
-		echo 'Name-Real: $2 $3' >> /tmp/genkey
-		echo 'Name-Email: $4' >> /tmp/genkey
+		echo 'Name-Real:' $2 $3 >> /tmp/genkey
+		echo 'Name-Email:' $4 >> /tmp/genkey
 		echo 'Expire-Date: 2y' >> /tmp/genkey
 		script -q /dev/stdout -c 'gpg --batch --gen-key /tmp/genkey' | tee /tmp/listo
-		
-		# capturar el valor de la llave
-		
+		millave=$(cat /tmp/listo | grep "gpg: clave" | uniq | awk '{print $3}')
+		export GPGKEY=$millave
 		rm -f /tmp/genkey
 		rm -f /tmp/listo
-		
-		echo "Llave Generada"
-		
-		echo "Listando las llaves generadas"
-		# exportar la llave generada ej: D8FC66D2 
-		# export GPGKEY=D8FC66D2
-		gpg --list-keys
-		pause "Presione Enter para continuar"
+		beep -r 3
+		echo ""
+		echo -e "\e[00;1;92mLlave GPG Generada.\e[00m"
+		gpg --send-keys --keyserver keyserver.ubuntu.com $millave
+		echo ""
+		echo -e "\e[00;1;92mSe envio al keyserver de Ubuntu la siguiente llave: $millave\e[00m"
+		mihuella=$(gpg --fingerprint $millave | grep "Huella de clave" | cut -c 25-74)
+		echo "$mihuella" | xclip -selection c
+		echo ""
+		echo ""
+		echo "Su huella esta almacenada temporalmente en el portapapeles."
+		echo "Siga las instrucciones a continuacion:"
+		echo ""
+		echo "1.- Abrir Launchpad.net en su navegador favorito y loguearse."
+		echo ""
+		echo "2.- Ir a firmar codigo de conducta."
+		echo ""
+		echo "3.- Registrar su nueva llave, en el campo fingerprint pegue lo que esta en el portapapeles (ctrl + v)"
+		echo "    presione el boton [Import Key]"
+		echo ""
+		echo "4.- Una vez realizada la accion anterior se le enviara un correo de confirmacion."
+		echo ""
+		echo "5.- Abra el correo que dice en el asunto: Launchpad: Confirm your OpenPGP Key"
+		echo "    copie el texto en el bloque gpg y peguelo en el bloc de notas, luego guardelo en su directorio /home/SU_USUARIO con el nombre correo.gpg"
+		echo ""
+		echo "6.- Luego presione Enter en la pantalla de la consola, donde se ejecuta el script"
+		echo "    se abrira una ventana del navegador por default donde hara clic en confirmar."
+		echo ""
+		echo "7.- Vaya de nuevo a firmar Codigo de Conducta y seleccione la opcion: 3 Sign it! (Firmar)"
+		echo ""
+		echo "8.- Pegue el contenido del portapapeles y presione continuar."
+		echo ""
+		pause "Presione Enter para continuar."
+		gpg --decrypt "$HOME"/correo.gpg > /tmp/descifrado
+		decrypt=$(cat /tmp/descifrado | grep https: | awk '{print $1}')
+		firefox $decrypt
+		pause "Presione Enter para continuar."
+		echo ""
+		echo -e "\e[00;1;92mSe firmara el codigo de conducta.\e[00m"
+		gpg --clearsign "$HOME"/"$minombre"
+		echo ""
+		echo -e "\e[00;1;92mEl codigo de conducta ha sido firmado.\e[00m"
+		cat "$HOME"/"$minombre".asc | xclip -selection c
+		rm -f /tmp/descifrado
+		rm -f "$HOME"/correo.gpg
+		echo ""
+		echo "Vaya a launchpad.net y presione ctrl + v para pegar el contenido del codigo de conducta ya firmado."
+		echo ""
+		echo -e "\e[00;1;92mFinalizado...\e[00m"
+		;;
 
-		#------
-
-		echo "Utiliza la terminacion pub la cual tiene una salida parecida a este"
-		echo "ejemplo (1024R/CE49EC21) y copia la cadena que esta despues del slash Ej. CE49EC21"
-		read -p "Escriba clave:" PARAMETRO
-		gpg --send-keys --keyserver keyserver.ubuntu.com $PARAMETRO 
-		#while [ $? != 0 ]; do
-		#	read -p "Escriba clave:" PARAMETRO
-		#	gpg --send-keys --keyserver keyserver.ubuntu.com $PARAMETRO
-		#done
-		gpg --fingerprint
-		echo "Pegar la huella digital que has copiado en la caja de texto Fingerprint,"
-		echo "a continuación, haga clic en el botón Import Key. Launchpad utilizará la huella"
-		echo "digital para comprobar su llave en el servidor de llaves de Ubuntu, y si tiene"
-		echo "éxito, te enviará un correo electrónico."
-		echo "Una ves importada la llave revise su correo ya que launchpad te envio un mensaje,"
-		echo "has click en el enlace que esta luego del texto: Please go here to finish adding"
-		echo "the key to your Launchpad account:"
-		echo "Al abrir el enlace se mostrara una pagina con una gran caja de texto"
-		echo "solicitandote un texto firmado. Bien copia el texto de confirmacion que aparece"
-		echo "en esa pagina el cual es algo similar a esto:"
-		echo "Please register 046439CD2486190A2C5A07390E6804DC16E7CB72 to the Launchpad user"
-		echo "Matthew Revell. 2007-01-26 12:50 UTC pegalo en un editor de texto, colocale un"
-		echo "nombre (ejemplo: confirmar.txt) y guardalo en tu carpeta personal."
-
-		#pause "Presione Enter para continuar"
-
-		#-------------
-
-		read -p "Escriba nombre archivo:" ARCHIVO
-		gpg --clearsign $ARCHIVO
-		#while [ $? != 0 ]; do
-		#	read -p "Escriba nombre archivo:" ARCHIVO
-		#	gpg --clearsign $ARCHIVO
-		#done
-		pause "Presione Enter para continuar"
-
-		echo "Firmado el archivo, fijate en tu carpeta personal aparece"
-		echo "un nuevo archivo llamado con una terminacion *.asc, abrir con un editor de"
-		echo "texto, copia y pega el contenido en la caja de texto de la pagina que abristes"
-		echo "con el enlace que te llego por correo y dale Continue."
-		echo "Ya con esto has agregado y confirmado tu llave GPG, ahora podemos pasar a firmar"
-		echo "el codigo de conducta. Firmando el Codigo de Conducta lo primero que hiciste al"
-		echo "comenzar con este script fue leer y descargar el Codigo De Conducta, por lo que"
-		echo "procederemos a firmarlo."
-
-		pause "Presione Enter para continuar"
-		gpg --clearsign UbuntuCodeofConduct-2.0.txt
-
-#-------------
-
+	ssh)
+		check
+		echo -e "\e[00;1;92mGenerando llave SSH\e[00m"
 		ssh-keygen -b 1024 -t rsa -f "$HOME"/.ssh/id_rsa -N ''
-		cat "$HOME"/.ssh/id_rsa.pub | xclip -selection c
-
-		echo "ir a launchpan.net y utilizar ctrl + v para pegar la llave ssh en el campo correspondiente"
-
-#-------------
+		echo ""
+		echo -e "\e[00;1;92mLLave SSH generada.\e[00m"
+		xclip -sel clip < ~/.ssh/id_rsa.pub
+		echo ""
+		echo "Su llave SSH  esta almacenada temporalmente en el portapapeles."
+		echo ""
+		echo "1.- Vaya a launchpad.net y haga clic en: ssh keys"
+		echo ""
+		echo "2.- Pegue (ctrl + v) el contenido del portapapeles y presione: importar public key"
+		echo ""
+		echo -e "\e[00;1;92mFinalizado...\e[00m"
 		;;
 
 	*)
-            	echo "USO: $(basename $0) {instalar|iniciar} nombre apellido tu@correo.com"
+            	echo "USO: $(basename $0) {instalar|gpg|ssh} nombre apellido sudireccion@correo.com"
 		;;
 
 esac
